### ISSUE TITLE
How to set up a local dev environment

### ISSUE THREAD

**Issue by kytrinyx** [exercism/bash#1]
See https://github.com/exercism/x-common/pull/28

See issue #2092 for an overview of operation welcome contributors.

---

Provide instructions on how to contribute patches to the exercism test suites
and examples: dependencies, running the tests, what gets tested on Travis-CI,
etc.

The [contributing document](https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md)
in the x-api repository describes how all the language tracks are put
together, as well as details about the common metadata, and high-level
information about contributing to existing problems, or adding new problems.

The README here should be language-specific, and can point to the contributing
guide for more context.

From the [OpenHatch guide](http://opensource-events.com/#project-setup):

> Here are common elements of setting up a development environment you’ll want your guide to address:
> 
> **Preparing their computer**
> Make sure they’re familiar with their operating system’s tools, such as the terminal/command prompt. You can do this by linking to a tutorial and asking contributors to make sure they understand it. There are usually great tutorials already out there - OpenHatch’s command line tutorial can be found here.
> If contributors need to set up a virtual environment, access a virtual machine, or download a specific development kit, give them instructions on how to do so.
> List any dependencies needed to run your project, and how to install them. If there are good installation guides for those dependencies, link to them.
> 
> **Downloading the source**
> Give detailed instructions on how to download the source of the project, including common missteps or obstacles.
> 
> **How to view/test changes**
> Give instructions on how to view and test the changes they’ve made. This may vary depending on what they’ve changed, but do your best to cover common changes. This can be as simple as viewing an html document in a browser, but may be more complicated.
> 
> Installation will often differ depending on the operating system of the contributor. You will probably need to create separate instructions in various parts of your guide for Windows, Mac and Linux users. If you only want to support development on a single operating system, make sure that is clear to users, ideally in the top-level documentation.

**Comment by adelcambre** [comment]
Can this be closed with the addition of https://github.com/exercism/xbash/blob/master/SETUP.md or does that need to be fleshed out more?

**Comment by kytrinyx** [comment]
The SETUP.md document is what gets included into all of the READMEs for the exercises. In retrospect that's totally not obvious, and probably not what you intended. We could move the contents of SETUP into the README (I don't think it needs to be fleshed out more).

**Comment by guygastineau** [comment]
Is this resolved now or is there more to do?

If there is, feel free to point me toward the work.

**Comment by budmc29** [comment]
@guygastineau you can actually help answer the questions here, was it easy for you to get everything set up and start contributing to the track?

**Comment by guygastineau** [comment]
Yeah, relatively easy.  This is the first time I have really used github in spite of some encouragement from friends in the past.  Mostly when I am trying to do something to contribute I have reached out here and read the README and Contributing guides for whatever repo I'm working with.  

- There isn't a lot of information about CI available but their error messages it gives are usually pretty clear
- by setting up do you also mean having access to bash?  I haven't seen any guides here on installing or configuring bash, but then again I didn't look.  I have been tweaking my preferred bash setups for the last 5 years.

**Comment by budmc29** [comment]
I'll close this since looks like it was straightforward enough for new developers to get started, and we have improved our documentation since this was opened.
