### ISSUE TITLE
Topics and difficulty

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#103]
As per issues #62 - #74, a list of topics need to be added to `config.json` for each exercise.

Looking over `config.json`, it seems that most exercises have a minimum of 2 topics listed. Should these open issues now be closed, or are they left open for any particular reason? I think that these have all been resolved and would like to close them.

@Smarticles101 would you agree? I like to minimise clutter so we are able to focus on the matters at hand. Additionally, in #4 you mentioned the range of difficulty in exercises didn't seem right. Do you think we should amend this by reviewing the current difficulties, or just seek to implement some more difficult exercises? :slightly_smiling_face: 

Edit: regarding reviewing difficulties, both `two-fer` and `word-count` are rated 2 here, but the [`word-count`'s example implementation](https://github.com/exercism/bash/blob/master/exercises/word-count/example.sh) seems to be a bit more complex than [`two-fer`'s example](https://github.com/exercism/bash/blob/master/exercises/two-fer/example.sh).

**Comment by sjwarner-bp** [comment]
I have just seen in #61 that Katrina has added some topics to each exercise, but would like someone more conversant in bash to review and amend.

I'll pick this up - this should de-clutter the issues a fair bit, allowing us to pick up some more discussion and move forward with launch plans! 🎉

**Comment by kotp** [comment]
As of this moment, it appears that:

* `hello-world`
* `leap`
* `error-handling`
* `pangram`

are marked as "core", which should indicate that it should unlock certain exercises.

For reference here:

* `gigasecond` unlocked by ``
* `bob` unlocked by ``
* `acronym` unlocked by ``
* `raindrops` unlocked by `leap`
* `difference-of-squares` unlocked by `leap`
* `armstrong-numbers` unlocked by ``
* `anagram` unlocked by `pangram`
* `hamming` unlocked by `pangram`
* `rna-transcription` unlocked by `pangram`
* `two-fer` unlocked by `pangram`
* `nucleotide-count` unlocked by ``
* `word-count` unlocked by `pangram`
* `phone-number` unlocked by `pangram`
* `triangle` unlocked by `leap`
* `atbash-cipher` unlocked by `hamming`

**Comment by sjwarner-bp** [comment]
That's great @kotp - thanks for doing that 🙂 

I think we are a bit too reliant on certain exercises. I've added a couple of suggestions in #109 which should diversify the track a little.

**Comment by sjwarner-bp** [comment]
Closed via #128
