### ISSUE TITLE
Run exercise tests through Travis

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#104]
As mentioned in #4, for each pull request, a run through all exercise tests would help maintainers quickly identify if the submission causes the tests to fail.

~Travis is currently used to lint submissions.~ <- incorrect! configlet lint is pulled in, but #116 talks about code linting.

**Comment by sjwarner-bp** [comment]
I personally have little experience in Travis, but am more than happy to look in to this if no-one else has experience - let me know :+1:

**Comment by Smarticles101** [comment]
I've got some experience with Travis. I might be able to work on this if I have time.

**Comment by sjwarner-bp** [comment]
Sounds good to me @Smarticles101

**Comment by budmc29** [comment]
@Smarticles101 any updates on this? If you are too busy I can give it a try this weekend.

**Comment by sjwarner-bp** [comment]
Fixed via #148 (Thanks! :slightly_smiling_face: )
