### ISSUE TITLE
Core exercises

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#109]
Looking through `config.json`, I have noticed we have few core exercises, but all exercises have an `unlocked_by`. I believe all 'optional' exercises need to be unlocked by core exercises (that's how it works on the Java track).

@exercism/bash Let me know if there is a reason we wouldn't have this policy, otherwise I'll adopt it and work on a fix.

**Comment by kotp** [comment]
There definitely should be some basis of "introductory" and then the unlocked exercises from there.... I think this is a good adoption.

**Comment by sjwarner-bp** [comment]
I am glad you agree @kotp - do you have any suggestions for which exercises should be "core"? I am going to be checking / amending the `config.json` as part of #103, and will be happy to tack this on afterwards 🙂

**Comment by kotp** [comment]
Currently, it looks like:
* `hello-world`
* `leap`
* `error-handling`
* `pangram`

Are the current "core" exercises.

**Comment by sjwarner-bp** [comment]
This is good to know - I'd suggest adding a couple more in, maybe a cipher based exercise and some arithmetic exercises. I think that:

* two-fer
* hamming
* armstrong-numbers
* atbash-cipher

are all good candidates to be added as core exercises. What does everyone else think @exercism/bash ?

**Comment by budmc29** [comment]
I agree for `hamming`, `armstrong-numbers`, `atbash-cipher` to be added.

Maybe we should add `bob` as well, since it's a fun but challenging exercise in bash that involves RegEx.

We should focus on 7-8 core exercises to match a similar ration for core to non-core exercises like othertracks, and then focus on adding more exercises to the track.

**Comment by budmc29** [comment]
Proposed core exercises:

1 `hello-world`
2 `leap`
3 `error-handling`
4 `pangram`
5 `hamming`
6 `armstrong-numbers`
7 `atbash-cipher`
8 `bob`

What do you think about these?

We can of course update them in the future, but at least we have a place to start.

**Comment by sjwarner-bp** [comment]
Agreed. I'll update my PR (apologies for being slow with that - hectic week!)

**Comment by sjwarner-bp** [comment]
Hi @budmc29. I am just looking over these, and I've realised that

`error-handling` cannot be both core AND `core: false`, `unlocked_by: none` as agreed in #128.

Currently, the core exercises stand as:

`grains`
`hello-world`
`reverse-string`
`armstrong-numbers`
`hamming`
`pangram`
`luhn`

This is a fairly good list, however I agree that some of the above should be added. I suggest adding `bob` and `atbash-cipher` as discussed above, and removing `reverse-string`.

This will leave us with 8 core, and a handful of `core: false`, `unlocked_by: null`.

**Comment by budmc29** [comment]
Closed by #128
