### ISSUE TITLE
Track policies (with a view to create POLICIES.md)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#114]
It would be most useful to have a succinct list of the current track policies, to allow future contributors (and reviewers) to facilitate the most desirable contributions.

This would also be a great reference tool, and would be a useful part of a template for PRs.

Before this PR, I'd like a discussion to take place regarding current policies (older members of @exercism/bash may have a better idea of longer-standing policies) and policies we should strive to implement/achieve.

**Comment by sjwarner-bp** [comment]
It seems like a good starting point would be "Plain Bash over POSIX compliance", as decided in #88.

**Comment by sjwarner-bp** [comment]
Another could be to formally record an onboarding process / document how we will ensure that onboarding is as easy as possible.

The Java track (where I have most experience) do this by having a number of good-first-patch issues open at any one time.

**Comment by sjwarner-bp** [comment]
Further, documenting the decision to come out of #87 would be beneficial to future contributors.

**Comment by budmc29** [comment]
This can be added: https://github.com/exercism/bash/issues/88#issuecomment-354574633

**Comment by budmc29** [comment]
Test structure can be added: #150
