### ISSUE TITLE
Where to keep HINTS.md

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#119]
In [`hello-world`](https://github.com/exercism/bash/tree/master/exercises/hello-world) the `HINTS.md` file is kept at the top-level of the `hello-world` directory, but in [`gigasecond`](https://github.com/exercism/bash/tree/master/exercises/gigasecond) the `HINTS.md` file is kept in a `.meta` folder inside of the `gigasecond` exercise directory.

We should decide the best place to keep these, and unify the code 🙂

**Comment by budmc29** [comment]
I'd go with keeping HINTS.md in top-level.
There are only a few exercises that have the need for that file (same goes for other tracks), and I don't see any downsides to keep it simple.

**Comment by sjwarner-bp** [comment]
I think that keeping it simple sounds good. I'll open a PR to fix this, and another to record this decision.
