### ISSUE TITLE
Improve ABOUT.md

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#129]
Currently, our [About the Bash Track](http://exercism.io/languages/bash/about) page is looking pretty empty in comparison to other tracks.

At the moment, it is just a quote and reference. For starters, I think the formatting could be improved, but overall the whole content could be improved. Paragraphs could include information about the history of Bash, where Bash is used (e.g. which systems), about the Bash community etc.

**Comment by budmc29** [comment]
Looks fine for me, and I agree that we can close it.
