### ISSUE TITLE
Git workflow advice for contributing.md

### ISSUE THREAD

**Issue by kotp** [exercism/bash#135]
#123 brought out the start of a discussion about `--force-with-lease` option on `git push`.  We should decide if this is the place for that advice, or if it should be removed, allowing for the contributor to decide how to manage their branch, or if it should be suggested as a practice that is good for more than just the Bash team.
  
Specifically [this comment in review](https://github.com/exercism/bash/pull/123/files#r159481661).

**Comment by sjwarner-bp** [comment]
While we *have* to advise on certain workflows (i.e. toolsets and processes), I feel like micromanaging smaller details could confuse less experienced users.

Personally, I think the reasonable thing would be to restrict advice/management of user workflows to a minimum.

**Comment by kotp** [comment]
Acknowledging the need to advise on tooling, `git` has been advised.  Advising the use of `--force-with-lease` or even `--force` is something that can be advised when it is necessary, so that we can be more likely to mention any complications that can result from that advice.  Either use is not a "simple" answer to a problem, as it definitely depends on the situation.
