### ISSUE TITLE
Add test versions in order to keep exercises up to date

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#136]
I think it would be worthwhile putting a `version` file in each exercise, indicating which version of the `problem-specifications` canonical data it is based off. This would be useful as the problem specs are updated fairly frequently with new test cases. We'd then be able to keep our exercises up to date!

Coming from the Java track myself, we stick a `version` file into each exercise, and then occasionally will run a script that checks against the problem specifications to indicate if an exercise is out of date. I think this is a really good way to do it, and would pose this as my suggestion.

To be more exact, we could use [this script](https://github.com/exercism/java/blob/master/scripts/canonical_data_check.sh) almost as is, and put a `version` file in a `.meta` folder per exercise. Each `version` check / PR could even be opened as good-first-patch issues.

This would not be for 'user' benefit as much as it would be for the @exercism/bash team.

**Comment by guygastineau** [comment]
@sjwarner-bp Did #140 take care of this? Should this issue be closed?

**Comment by kotp** [comment]
I believe it is only a partial step to completing this.

**Comment by sjwarner-bp** [comment]
#140 was just to add a script that will allow us to check versions of the tests against the canonical data. For us to be able to use this script, we need a `.meta/version` to be added to each exercise. The easiest way to do this will be to bring all tests in an exercise up to date and then label it with that particular version number.

**Comment by guygastineau** [comment]
#185 is realated to this as it attempts to streamline updating tests.
- The generator could also possibly make or overwrite the version file in .meta after the test has been generated. What do you guys think?

**Comment by guygastineau** [comment]
PR #186 is the first test version update done with the generator I'm building.

I should be able to get all our exercises up to date and with `./meta/version` files this week.

**Comment by guygastineau** [comment]
More than half-way to closing this issue!
