### ISSUE TITLE
Travis CI master build

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#137]
While PR branches are building, it looks like master hasn't been building for the last 5 months.

I think I know why, and where to enable that - I've just opened this as a placeholder, and a suitable place to raise any problems if they do come up. If there aren't problems, I'll close it.

**Comment by sjwarner-bp** [comment]
I think I've enabled master to build again. This should automatically be triggered next time a PR is merged - once there is a PR ready to merge, we will find out 🙂

**Comment by kotp** [comment]
Any notes to show what you did for this?

**Comment by sjwarner-bp** [comment]
[This comment here](https://github.com/exercism/discussions/issues/174#issuecomment-318855073) seems to explain why master is not building - notice "Build branch updates" is turned off.

All I have done is re-enabled "Build branch updates". In the event that this causes more problems than it solves, we can swap it back 🙂

**Comment by sjwarner-bp** [comment]
N.B. it looks like master is building again - it passed on last merge [here](https://travis-ci.org/exercism/bash/builds/325924294)
