### ISSUE TITLE
Exercise README insert

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/bash#138]
In #130 and #131, changes to READMEs have been merged in that alter the test command from `bats whatever_test.sh` to a test command that includes the exercise slug (as it will appear in each exercise directory).

However, if this is the convention others have chosen to go with, this now means that generating READMEs using configlet will not work properly, as configlet will pull the [insert](https://github.com/exercism/bash/blob/master/docs/EXERCISE_README_INSERT.md) in automatically.

So, in order to stay consistent across the READMEs, I suggest either changing the command to something more obviously a placeholder for the slug name (e.g. `bats <slug_name>_test.sh`) or using the `.Spec.SnakeCaseName` found [here](https://github.com/exercism/configlet#the-readme-template). I recommend either one of these, as the current method would mean automatically generating most of the README, then manually changing parts, which could lead to error/inconsistency.

**Comment by sjwarner-bp** [comment]
I'm happy to have a look into changing this for `.Spec.SnakeCaseName` as that would be in keeping for the current convention that seems to have been merged in #130 and #131.

**Comment by budmc29** [comment]
This sounds good to me, if you have time give it a try and let's see how it goes.

> I'm happy to have a look into changing this for .Spec.SnakeCaseName

That would be awesome. All the tools are created language agnostic and some conventions are arbitrary, so we need to translate everything we implement to `bash` conventions.

I try to follow this style guide: https://google.github.io/styleguide/shell.xml, and while is not 100% agreed on by every bash developer I think most of it should be fine, and in cases where we disagree we can discuss.
Following this, in my opinion, is way better than following conventions from other languages.

**Comment by sjwarner-bp** [comment]
This has been done in #139
