### ISSUE TITLE
Ensure Bash track is ready for v2 launch

### ISSUE THREAD

**Issue by kytrinyx** [exercism/bash#168]
There are a number of things we're going to want to check before the v2 site goes live. There are notes below that flesh out all the checklist items.

- [x] The track has a page on the v2 site: https://v2.exercism.io/tracks/bash
- [x] The track page has a short description under the name (not starting with `TODO`)
- [x] The "About" section is a friendly, colloquial, compelling introduction
- [x] The "About" section follows the formatting guidelines
- [x] The code example gives a good taste of the language and fits within the boundaries of the background image
- [x] There are exercises marked as `core`
- [x] Exercises have rough estimates of difficulty
- [x] Exercises have topics associated with them
- [x] The first exercise is `auto_approve: true`

## Track landing page

The v2 site has a landing page for each track, which should make people want to join it. If the track page is missing, ping `@kytrinyx` to get it added.

### Blurb
If the header of the page starts with `TODO`, then submit a pull request to https://github.com/exercism/bash/blob/master/config.json with a `blurb` key.  Remember to get [configlet](https://github.com/exercism/configlet/releases/latest) and run `configlet fmt .` from the root of the track before submitting.

### About section
If the "About" section feels a bit dry, then submit a pull request to https://github.com/exercism/bash/blob/master/docs/ABOUT.md with suggested tweaks.

#### Formatting guidelines
In order to work well with the design of the new site, we're restricting the formatting of the `ABOUT.md`. It can use:

* Bold
* Italics
* Links
* Bullet lists
* Number lists

Additionally:

* Each sentence should be on its own line
* Paragraphs should be separated by an empty line
* Explicit `<br/>` can be used to split a paragraph into lines without spacing between them, however this is discouraged.

### Code example
If the code example is too short or too wide or too long or too uninteresting, submit a pull request to https://github.com/exercism/ocaml/blob/master/docs/SNIPPET.txt with a suggested replacement.

## Exercise metadata
Where the v1 site has a long, linear list of exercises, the v2 site has organized exercises into a small set of required exercises ("core").

If you update the track config, remember to get [configlet](https://github.com/exercism/configlet/releases/latest) and run `configlet fmt .` from the root of the track before submitting.

### Topic and difficulty
Core exercises unlock optional additional exercises, which can be filtered by topic an difficulty, however that will only work if we add topics and difficulties to the exercises in the track config, which is in https://github.com/exercism/bash/blob/master/config.json

### Auto-approval
We've currently made any hello-world exercises auto-approved in the backend of v2. This means that you don't need mentor approval in order to move forward when you've completed that exercise.

Not all tracks have a hello-world, and some tracks might want to auto approve other (or additional) exercises.

## Track mentors
There are no bullet points for this one :)

As we move towards the launch of the new version of Exercism we are going to be ramping up on actively recruiting people to help provide feedback. Our goal is to get to 100%: everyone who submits a solution and wants feedback should get feedback. Good feedback.

If you're interested in helping mentor the track, check out http://mentoring.exercism.io/

#
When all of the boxes are ticked off, please close the issue.

Tracking progress in https://github.com/exercism/meta/issues/104

**Comment by sjwarner-bp** [comment]
This all makes sense to me - I think we are already compliant with a handful of the points provided here. I'll go through it all a little closer later on and double check :slightly_smiling_face:

**Comment by jackhughesweb** [comment]
`config.json` currently has `active` set to false - I don't think this is currently a major issue (there is a v2 page for this track), but I'm not sure whether this is intentional or not?  🙂

https://github.com/exercism/bash/blob/5064f479a952e8c3eabc5bd3b185adf62a876904/config.json#L2

**Comment by sjwarner-bp** [comment]
Hi @jackhughesweb - thanks for the comment!

I think that is deliberate, because currently the bash track isn't actually "launched". If you check out [the languages page](http://exercism.io/languages) it is listed under 'upcoming'.

We've got an issue #4 open to track our launch plans. We're close, but work has slowed a bit since January.

**Comment by sjwarner-bp** [comment]
Hey @kytrinyx - just to double check a couple of these points (I think we're close to being all good over here):

- How often does the v2 website get regenerated? I added a blurb yesterday, so just waiting for it to show up
- The current 'About' section contains a quote. I want to check that quotes aren't supported, as they aren't mentioned in the formatting section. I'm more than happy to strip it out and add the essence of what was said, just want to make sure first 🙂

**Comment by kytrinyx** [comment]
Under normal circumstances I think the new code would get pulled in immediately (we have webhooks listening for changes on master of the tracks). I will check with the others what's up with this.

> The current 'About' section contains a quote and code snippets. I want to check that quotes and code aren't supported, as they aren't mentioned in the formatting section.

Yepp, that's correct.

**Comment by sambhav2612** [comment]
I guess the `About` Section does follow the said formatting guidelines. Having said that the checklist is complete and the issue can be closed.

**Comment by kytrinyx** [comment]
@sambhav2612 Thanks!

**Comment by budmc29** [comment]
@kytrinyx can you please let us know what else do we need in order to get the Bash track into the new Exercism.io platform?

**Comment by kytrinyx** [comment]
> I assumed we had everything that was needed, but looks like that's not the case.

Why is that?

I'm pretty sure all you need to do is update the `active` key in `config.json` to say `true`.

**Comment by budmc29** [comment]
Ah, okay, than that's great, I assumed we needed more.

I'll create a PR with that, thank you.
