### ISSUE TITLE
Bash track still isn't active on exercism.io

### ISSUE THREAD

**Issue by guygastineau** [exercism/bash#175]
After PR #174 I hoped to find bash listed as active on exercism.io.
As of now it is not present and the search bar will not find it on the site.

**Comment by budmc29** [comment]
@kytrinyx are we missing something, or we need to wait for the next deploy?
Thank you.

**Comment by sjwarner-bp** [comment]
I think it will be a case of waiting for a deploy - sometimes these changes take a little while to get to the live site :slightly_smiling_face: 

I'm not sure on the schedule for that though. It took a day or so for the track bios to appear after I'd added it.

**Comment by budmc29** [comment]
Good to know.

**Comment by budmc29** [comment]
You can access the track in the meantime with: https://exercism.io/my/tracks/bash

**Comment by guygastineau** [comment]
@budmc29. Thanks.  That's what I've been doing.

**Comment by guygastineau** [comment]
It has been manually activated @iHiD.
