### ISSUE TITLE
Bob_test.sh tests need fixing

### ISSUE THREAD

**Issue by guygastineau** [exercism/bash#178]
- The shouting with umlauts test is broken.
- Also, they aren't umlauts.
- Also, other tracks don't seem to have these two tests.
### Requesting permission to remove these two tests in a PR

**Comment by guygastineau** [comment]
Additionally, the forceful question test expects `"Whoa, chill out!"` when it should be `"Calm down, I know what I'm doing!"`

**Comment by budmc29** [comment]
Can you explain your first two points? We need more details.

**Comment by sjwarner-bp** [comment]
I think that this has been discussed in the problem-specifications track to some extent? There were a couple of issues on certain platforms around the useage of non-ascii characters: https://github.com/exercism/problem-specifications/issues/441

This issue boils down to the fact that this test is not up to date. The entire test suite should be brought up to date with the canonical data (over here https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json)

**Comment by guygastineau** [comment]
Thanks guys for your responses. I will update the Bob problem to the most current problem-specifications data.

**Comment by guygastineau** [comment]
I have fixed bob.sh, I believe but I accidentally merged my branch for #177 into my fork master so making a PR for my fix-bob.sh branch tried to submit my commits found there too.  I'll open the PR for this when my other PR goes through

**Comment by budmc29** [comment]
#177 merged.

**Comment by guygastineau** [comment]
thanks @budmc29

**Comment by budmc29** [comment]
Can you please answer my question about your first two points? 
https://github.com/exercism/bash/issues/178#issuecomment-406182010

**Comment by guygastineau** [comment]
Okay,
- a test can be made either to pass shouting with umlauts or pass calmy speaking with umlauts.
- the characters in that part of the test are not actually umlauts. In German an umlaut operates on vowels by representing a simple dipthong. 
- while umlaut basically just means sound change, traditionally it is only used to reference two dots above a letter that can be upper or lower case.
  - the symbols used in those two tests looked like little capital A's, which don't seem to have a case.

**Comment by guygastineau** [comment]
Opened #184 just now.
I didn't want to open a new PR for it but I managed to get my fork of exercism/bash fubar.
Everything should be able to move forward now.

Also @budmc29 Is everything regarding the unlaut tests clear, now?

**Comment by budmc29** [comment]
I don't know enough to argue if those are umlauts or not, but if they cause issues then it's better to remove them since they are not in the canonical data.
