### ISSUE TITLE
Updating Grains: Include last case?

### ISSUE THREAD

**Issue by guygastineau** [exercism/bash#197]
Our grains test has all but the last test case from the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/grains/canonical-data.json).

It is the one that wants the total count for all the grains on the board.

Should I include it in my upcoming update and change the `example.sh` to pass, or should I leave the problem as is?

**Comment by guygastineau** [comment]
I did get the example to pass the test but it took some thorough reworking.

I think adding the last test gets the student to think some about structure.

Here is the new example.sh

```bash
#!/bin/bash

INPUT="$1"

get_grains () {
  local index=$(($1-1))
  printf "%u\n" "$(( 2 ** index ))"
}

if [[ "$INPUT" == "-A" ]]; then

  for square in {1..64}; do
    sum=$(( sum + $(get_grains "$square")))
  done
  printf "%u\n" "$sum"

elif [[ "$1" -lt 1  || "$1" -gt 64  ]]; then

    echo "Error: invalid input"
    exit 1;

else
get_grains "$INPUT"

fi
```

**Comment by guygastineau** [comment]
the old one is:
```bash
#!/bin/bash

if [[ "$1" -lt 1  || "$1" -gt 64  ]];
then
    echo "Error: invalid input"
    exit 1;
else
    index=$(($1-1))
    echo "2^$index" | bc;
fi;
```

**Comment by kotp** [comment]
Create a merge request for this...

**Comment by guygastineau** [comment]
Cool I'll PR the test, example, and version once #198 goes through.
