### ISSUE TITLE
leap: Unable to run tests

### ISSUE THREAD

**Issue by ZapAnton** [exercism/bash#200]
In the leap exercise if I run `bats leap_test.sh`, I would always get an error:
```shell
 `[ "$status" -eq 0 ]' failed
```
regardless of the actual returned value in my script.

I tried to run and [example solution](https://github.com/exercism/bash/blob/master/exercises/leap/example.sh), and it also fails with the same error.

But when I replaced 
```shell
run ./leap.sh 2015
```
with
```shell
run bash leap.sh 2015
```
everything is fine in that test case.

Is there a problem on my end? Maybe i should run bats with a different configuration?

**Comment by sjwarner-bp** [comment]
This sounds like a permissions issue - what does the file permissions read as when you run `ls -l`

**Comment by budmc29** [comment]
@ZapAnton we're moving towards using `run bash exercise.sh` on all our tests, feel free to open a PR if you would like to help fix this.

Example PR: https://github.com/exercism/bash/pull/177/files

**Comment by budmc29** [comment]
As a quick fix, you can update your test and submit them with the solution.
