### ISSUE TITLE
Bash test files shebang

### ISSUE THREAD

**Issue by budmc29** [exercism/bash#236]
I'm currently working on  #234 which will add automatic checking for our files to `travis`.

One of the issues with the linter is that it's not recognizing the `#!/usr/bin/env bats` shebang.

Since we don't use the `bats` convention and we have `exercise.sh` instead of `exercise.bats`, I think we are fine to update the shebang to be `#!/usr/bin/env bash`.
That should not make any difference since we're moving away from calling the tests directly from the CLI and our users are instructed to use `bats file_name.sh`.

If no one has any objection to this, I'll create a PR later to change those.

@exercism/bash

**Comment by guygastineau** [comment]
Sounds fine to me.
