### ISSUE TITLE
Unlocking nucleotide count

### ISSUE THREAD

**Issue by guygastineau** [exercism/bash#247]
Do you all think that nucleotide count should be unlocked by Hamming instead of Hello-world?

Personally I think that nucleotide count is easier than Hamming, but I also think it is thematically tied to Hamming.

Let me know what you think.

@exercism/bash-contributors

**Comment by budmc29** [comment]
Looks like `nucleotide-count` is not unlocked by hello-world, or am I missing something?

I have nothing against unlocking it by `hamming`, so feel free to open a PR.

**Comment by guygastineau** [comment]
Yeah, I just checked it again and it isn't. I don't know why I thought it was.

Thank you for the feedback.  I'll make a PR sometime this week.

**Comment by guygastineau** [comment]
I should have time to do this tomorrow.
