### ISSUE TITLE
Triangle Test: Needs Unique Names

### ISSUE THREAD

**Issue by troberson** [exercism/bash#263]
The "skip" feature of "bats" requires all tests to have unique names. Otherwise, all tests with the same name are skipped.

![triangle](https://user-images.githubusercontent.com/1380069/46578156-b00d0000-c9ac-11e8-8335-d397d866f19a.png)

Here is a patch to rename the tests to be both unique and more descriptive: 
https://gist.github.com/troberson/b2f0c6c3f116f036d49218f0545c90f6

![triangle2](https://user-images.githubusercontent.com/1380069/46578163-0b3ef280-c9ad-11e8-9ac9-69661eb9afd3.png)

**Comment by budmc29** [comment]
I have commented on the PR, and I think making the tests have better names would help all the repositories not just ours (even if it's a quirk of Bats).

If people disagree with that, then we'll just merge the PR as it is.

**Comment by budmc29** [comment]
Will close this, feel free to reopen if you have time to complete it.
