### ISSUE TITLE
Hello World exercise

### ISSUE THREAD

**Issue by CivZero** [exercism/bash#272]
Please help. I'm losing my mind trying to figure out what I did wrong. I made sure that the output is exact, that the bats version is updated and that the .sh's are executable. I have even tried copying someone else's code and it still isn't working for me. 

```
#!/usr/bin/env bash

set -o errexit
set -o nounset

main() {
  input=$1
  echo "Hello, World!"
}

main "$@"
```
Sorry, forgot to post error message. 
![screen shot 2019-03-07 at 8 36 12 pm](https://user-images.githubusercontent.com/6953162/54003708-b698d280-4118-11e9-802d-48cccb986e7d.png)

**Comment by NobbZ** [comment]
1. The file does not need to be executable, as the tests do `bash hello_world.sh`
2. If you call the script from the shell manually, using the same invocation as in the tests (look them up please, to be exact) what do you see then?
3. Have you checked if you have named the file exactly as expected? Taking care of the casing behaviour of your file system?

**Comment by NobbZ** [comment]
Ps, $1 is not set, therefore the script will panic on line 7.

You do not need that anymore, remove that line and it will probably work.

**Comment by CivZero** [comment]
Thanks, everyone for responding. Sorry for posting this in the other thread, I'm still somewhat new to Git so I'm learning the ins and outs. I was finally able to get this working so thank you all very much for the info.
