### ISSUE TITLE
Exercise 1 problem

### ISSUE THREAD

**Issue by chrisAhmed** [exercism/bash#273]
Hello! So I'm a bit confused with this first exercise. It says to comment out or remove "skip" annotations prepending other tests. What other tests are there and where are these "skip" annotations? 

Also, bats throws an error for the test shell script with the following:

/* 
 ✗ Say Hi!
   (in test file hello_world_test.sh, line 6)
     `[ "$status" -eq 0 ]' failed
*/

Is that what we are supposed to fix? (iI'm using Ubuntu on WSL for a learning environment if that information is needed)

Thanks for your help and have a great day!

**Comment by NobbZ** [comment]
The testsuite for `hello-world` does not contain any `skip`ed tests, so you can't remove any `skip`s there. Just remember that remark for subsequent exercises.

The error message you quote though, tells us, that the script under test did not exit with an exit code of `0`. This can have many reasons.

What is the actual content of your `hello_world.sh`? And what is the output of `bash hello_world.sh; echo $?`?

**Comment by chrisAhmed** [comment]
Hi NobbZ, thanks for your help.

It's the default script that was packaged with the exercise. It doesn't say to edit anything so I haven't done anything to it. The following:
`bash hello_world.sh; echo $?`
results in 
`hello_world.sh: line 17: $1: unbound variable`
`1`

**Comment by NobbZ** [comment]
Of course you need to edit the script, that's the overall cause of doing the exercises, what is the fun in getting the solution with the exercise?

And now, you know what's causing the error, now it should be easy to fix.

**Comment by chrisAhmed** [comment]
I knew there was _something_ to do, but not exactly what as these instructions seem to be a bit vague especially for someone brand new to bash and this type of learning environment. 

For example, with the skip annotations comment, I was spending far too much time trying to figure out what that exactly meant only to realize (from your message above) that it will be useful to know only for further exercises. Also, after this clarification, I'm assuming "test suite" is not a _suite_ per se, but simply bats and hello_world_test.sh in which running that script calls hello_world.sh for debugging purposes and the above mentioned errors are actually with hello_world.sh and not the test script itself. The exercise flat out states to just write a function, not mentioning writing the function in hello_world.sh leaving me thinking I would just create some script to write it and call it a day. If I did such I would completely bypass this test suite and call it a day thinking I did the right job.

Call me whiny, but these are some of the issues that popped up in my head. If just a little more information was added, approaching this track would be a bit less disconcerting. I bet 99% of the people doing this understood exactly what to do. Just wanted to give a differing opinion is all.

**Comment by NobbZ** [comment]
Sadly there is nothing what we could do about the phrase "function", as the README is generated from a central description, and the word "function" suites the needs for about all tracks but a few.

I do understand though, that the "skip" part might be confusing at first, but once you get it, its fine :) But I think, that it should be possible to remove that comment from `hello-world` and move it to the follow up exercise, which actually has some tests to skip.

The suite though, well, yes. Its only a single file, but except for `hello-world` it contains more than one test case, so I think we could call it "suite". `bats` though is the testing framework and runner.

@exercism/bash could you perhaps take a closer look into how to clarify the instructions?
