### ISSUE TITLE
Reorganizing Exercises

### ISSUE THREAD

**Issue by guygastineau** [exercism/bash#287]
Now that we have more (and harder) exercises I think we need to rethink our core exercises, and then apply a new unlocking scheme.

Thanks to @glennj we have a slew of new ports coming in https://github.com/glennj/bash/branches/active

It might be easier to accept suboptimal unlocking relationships for now, and then tackle this project once all the exercises from the above link have made it into the track.

**Comment by glennj** [comment]
Do we also want to review the topics? I've noticed that we've strayed from (what I assume is) the canonical [list of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt).

In reordering relationships, how much do we want to allow ourselves to be influenced by other language tracks?

**Comment by guygastineau** [comment]
I think looking at some of the more systematic language tracks is a good idea.

Some exercises will have the same tags in all languages, but the tags are intentionally left up to the track.  Some languages have wildly different ways of handling the same problem which leads to different tags.

Still observing the tags used elsewhere can ensure we don't omit relevant tags.

I think in the ten months I've been a maintainer here there was 1 minor restructuring of the track, but most of what we're dealing with is older than that.

@glennj given the amount of ports you have coming in do you want to:
1) rework track order/unlocking before they're all merged?
2) rework what we have now, and then reassess as we go?

Personally I think we will be more effective and efficient if we wait until your current pipeline has been exhausted.

**Comment by guygastineau** [comment]
Yes, I believe that our topics shouldn't stray from that list.  If we think a topic needs to be used it should be PR'd there first.

**Comment by glennj** [comment]
I still am working on more ports. I think I'll pause this issue for now (for me).

**Comment by guygastineau** [comment]
Sure, I appreciate your diligent efforts, and I think once you get us to 50+ exercises we will be in a very good place to organize our track well.

**Comment by glennj** [comment]
I've ported as many exercises as I think are appropriate.

I've put together a grid to list the current parent-child relationships, and the tags for each exercise. See [this google sheet](https://docs.google.com/spreadsheets/d/14c1oovaMJeHvxBWpCk6BqX_XYqNBgLHfQ1WKsM-zye8/edit?usp=sharing). Next step is to  re-parent the non-core exercises as appropriate and to normalize the tags. I'll be adding another worksheet to track the changes.

**Comment by glennj** [comment]
I've taken my stab at reorganizing and re-keywording the exercises (based largely on the Ruby track). Please see [the google sheet](https://docs.google.com/spreadsheets/d/14c1oovaMJeHvxBWpCk6BqX_XYqNBgLHfQ1WKsM-zye8/edit?usp=sharing).

**Comment by guygastineau** [comment]
Thanks for taking initiative on this.  I am taking a look now ;)

**Comment by guygastineau** [comment]
Excellent work on these google-sheets.

I'll think about it today, and do some additional thought organization.  Remind me if I haven't gotten back to you about this in a day or two ;)

**Comment by guygastineau** [comment]
Once we get the link from @IsaacG ordering the exercises by difficulty I think we should work our way through the sanity of the difficulty ratings, before finalizing our thoughts on core/child relationships in the track.

This should also give us some time to catch our info up with the new ports @glennj has been rolling out.

**Comment by IsaacG** [comment]
$  jq -r '.exercises|.[]|"\(.difficulty) \(.slug)"' config.json | sort -n

1 hello-world
1 reverse-string
1 two-fer
2 allergies
2 armstrong-numbers
2 difference-of-squares
2 error-handling
2 grains
2 hamming
2 house
2 largest-series-product
2 leap
2 pangram
2 raindrops
2 resistor-color-duo
2 rna-transcription
2 scrabble-score
2 secret-handshake
2 series
3 acronym
3 anagram
3 beer-song
3 bob
3 collatz-conjecture
3 isogram
3 matching-brackets
3 nucleotide-count
3 phone-number
3 prime-factors
3 proverb
3 rotational-cipher
3 sieve
3 space-age
3 triangle
3 twelve-days
3 word-count
4 all-your-base
4 binary-search
4 diamond
4 gigasecond
4 isbn-verifier
4 luhn
4 pig-latin
4 roman-numerals
5 atbash-cipher
5 diffie-hellman
5 food-chain
5 grep
5 run-length-encoding
5 say
6 affine-cipher
6 yacht
7 forth
8 change
9 two-bucket

**Comment by glennj** [comment]
Whenever we want to revisit this, I'm happy to participate.

**Comment by glennj** [comment]
I think, with exercism v3, this is no longer relevant.
