### ISSUE TITLE
Enforceable Style-Guidlines for Contributions

### ISSUE THREAD

**Issue by guygastineau** [exercism/bash#367]
Currently we have a loose reference to an external style-guide that is not enforced.

It should be clear that this is not meant to be a style enforced on our students by mentors.

I propose that we create a clear, enforceable, in-house style-guide that is applied/enforced on all contributions.  This project may be started as a PR, but it is also fine for us to flesh out some ideas/preferences here before that gets underway.

The completion of this project will also necessitate changes to our docs on contributing.

**Comment by guygastineau** [comment]
I would like to address the following question rather immediately:
### Shouldn't we change our file and directory naming schema to `kebab-case` instead of `snake_case`?

Personally I see no reason to convert our slugs between these two conventions. Furthermore, who really likes underscores?!?

Well, that is probably a bit too emotional.  I wont make this change unless there is majority support, but for the record I think it would an excellent improvement.

**Comment by kotp** [comment]
I believe the snake case is something that effects things at a higher level than just the track.  (from memory, not recently researched).

**Comment by guygastineau** [comment]
You are probably right.

That aspect should be out in hold until we can get verification.

**Comment by kotp** [comment]
I can check this later, just need to browse around to a few different tracks and verify, or look for snake_case in the issues for `exercism/exercism` maybe.

**Comment by guygastineau** [comment]
@kotp thank you :heart:

**Comment by kotp** [comment]
For the ones I checked, the languages that prefer not using camelCase style file names use dash for the exercise name (folder) and underscore for multi-word names.

So currently, leaving the standard as `shish-kebab/snake_case` as it is now is probably the thing to do.  We may have some choice as to the file name themselves, but I don't believe we have freedom for the exercise directory name style at the "track" level.

**Comment by guygastineau** [comment]
You are right.  All of the exercise directories expected to be kebab-case.  The thing that gets me about sbake-casing the filenames is that I can't see the reason behind it.

It is harder to type, and it forces all of our scripts to convert between the kebab exercise slug at the directory level and the snake interpretation of that same slug.

If other tracks are using camelCase for their exercises, then this might mean we are not forced to follow the convention.

**Comment by kotp** [comment]
Some other languages are using this camelCase, because their language has adopted this.  Also, another consideration is that `_` is not used to indicate an option while `-` is.  In a line of commands, this can sometimes be hard to see, especially if it is at the end of a terminal screen, and unsure if there is a space there that you can't detect. (This is the human aspect, a program would be able to detect it).

I prefer the underscores, and not sure what you mean by harder to type.  It is in exactly the same position as the `-` (except for the one on the numeric keypad) on qwerty keyboards.  At least as easy to type as any other shifted and unshifted character pairs.

**Comment by guygastineau** [comment]
You make a good point about accessibility.

I just hate simultaneous key presses :smiling_imp: 

I am also annoyed every time I have to transform it to a slug or transform from a slug to the snake_case version, but I can live with it.  I think it provides more opportunities for error in it's current state than it would in kebab-case though :stuck_out_tongue_closed_eyes:

**Comment by kotp** [comment]
Make a library that we can load to do that in a function... ?

**Comment by guygastineau** [comment]
I merged committed #370 instead of squash comitting it. I guess I didn't realize that It turned a single commit into two (the real commit and the merge commit).

Historically we have been squash and merging since before I started here.

I know there is some sort of crazy debate in the wider world about how to handle history (and apparently the sides are as entrenched as the vim-vs-emacs wars).  I don't think that #370 ruins the clarity of our history, so I wont be trying to clean that out of it (if I understand correctly we would all have to rebase our forks or something wildly unnecessary like that)

Anyway, I just wanted to make a note here, that in the maintainers guide we should decide exactly the right protocol to enforce (that way if I mess it up you guys should feel free to yell at me ;) )

**Comment by kotp** [comment]
The history is still pretty... no worries.  Squash and merge when there are commits that are minor and don't need a description or a commit point, merge when the history will still make sense.  Rebase and merge when it makes sense to do so.  Having a perfectly single level history can make sense, but it isn't disaster when it doesn't.  Avoid undue noise, but when the noise comes in, it's OK too.
