### ISSUE TITLE
Questions arise while implementing list-ops exercise as library implementation

### ISSUE THREAD

**Issue by glennj** [exercism/bash#375]
I’m implementing [list-ops](https://github.com/exercism/problem-specifications/tree/master/exercises/list-ops) as a library, and I've got some questions about the best way to proceed. Consider
```sh
source list_ops.sh
double() { echo $(( $1 * 2 ));}
list=( 1 2 3 4 )
list::map double list   # or
list::map double "${list[@]}"
```

Should the array be passed by name, or should the elements be passed? For a `map` function it doesn't really matter, but if the list function is something like `intersection` it would make more sense to pass 2 array names.

Also, struggling with the best way to return a result array:

* the safest way is to force the user to pass an array name:
```
result=()
list::map double list result    # in some order
printf "%s\n" "${result[@]}"
```

* the simpler method, command substitution, is subject to word splitting and globbing:
```
result=( $( list::map double list ) )
```

**Comment by glennj** [comment]
For testing, this is what I’ve got in the test script (pending this discussion): `run` receives an inline bash script.
```sh
@test "map non-empty list" {
    [[ $BATS_RUN_SKIPPED == true ]] || skip
    run bash -c '
        source list_ops.sh
        list=(1 3 5 7)
        incr () { echo $(( $1 + 1 )); }
        #result=( $(list::map incr "${list[@]}") )
        result=( $(list::map incr list) )
        echo "${result[*]}"
    '
    [[ $status -eq 0 ]]
    [[ $output == "2 4 6 8" ]]
}
```

**Comment by glennj** [comment]
Relates to https://github.com/exercism/bash/pull/373

**Comment by glennj** [comment]
Just tried another take in the test file:
```
setup() { source list_ops.sh; }

@test "foo" {
    run bash -c '
        list=(1 3 5 7)
        incr () { echo $(( $1 + 1 )); }
        result=( $(list::map incr list) )
        echo "${result[*]}"
    '
    [[ $status -eq 0 ]]
    [[ $output == "2 4 6 8" ]]
}
```
The test failed due to the list::map function _not existing in `run`'s shell.

This way of writing the tests forces the library to `export -f` each function.

Is that something a shell library should do?

**Comment by IsaacG** [comment]
bash sucks at this sort of thing. Consider using known list names. listA listB result. The function is responsible to read from those lists and write to that list.

The only real alternative is to pass variable names all over and use indirection.
