### ISSUE TITLE
Issue with test on Sieve exercise for Bash track.

### ISSUE THREAD

**Issue by DERPSQUID9** [exercism/bash#382]
My script for Sieve on the Bash track appears to output the same values as expected by the test script when I run it on its own, but it only ever passes the first two tests no matter what I do.

**Comment by iHiD** [comment]
FYI, I've moved this to exercism/bash

**Comment by IsaacG** [comment]
So ... bats `run` changes the IFS.

```
@test 'basic' {
  n=$IFS
  [[ $n = "$IFS" ]]
  run bash -c 'echo "${a[@]}"'
  [[ $n = "$IFS" ]]
}
```

^^ fails on the second test. But passes the first.

```
@test 'basic' {
  echo Before
  echo "$IFS" | od -c

  run bash -c 'echo "${a[@]}"'
  echo After
  echo "$IFS" | od -c

  false
}
```

prints

```
   Before
   0000000      \t  \n  \n
   0000004
   After
   0000000  \n  \n
   0000002
```

So the IFS is being set to `\n` where it generally is `space-tab-newline`. Which means the output gets newline-separated vs space.

**Comment by IsaacG** [comment]
There's a bug in the test tool [here on L61](https://github.com/sstephenson/bats/blob/03608115df2071fff4eaaff1605768c275e5f81f/libexec/bats-exec-test#L61). Rather than assigning IFS for the one line where they want to split the output on newline, they are actually permanently assigning a new value to IFS in the format of `a=1 b=2` which assigns two vars.

I'll submit an upstream patch.

**Comment by IsaacG** [comment]
Fun fact, that bats repo has: Latest commit 0360811 on Feb 19, 2016.

It might not get fixed. Work around might require us setting IFS=$' \t\n' in the test code after doing a `run`

**Comment by glennj** [comment]
PR https://github.com/exercism/bash/pull/383 takes another approach: don't use arrays for expected data in the tests.

**Comment by glennj** [comment]
That PR has been merged. You can navigate to your sieve solution and update to the latest test version. Re-download and verify your working code.

**Comment by guygastineau** [comment]
@DERPSQUID9 can you confirm your solution is working now?

**Comment by DERPSQUID9** [comment]
@guygastineau I sure can!
