### ISSUE TITLE
Duplicate tests for Triangle exercise

### ISSUE THREAD

**Issue by ovidiu141** [exercism/bash#384]
All 3 tests for 'triangle inequality violation' have the same code:

```
  [[ $BATS_RUN_SKIPPED == true  ]] || skip
  run bash triangle.sh isosceles 1 1 3
  [[ $status -eq 0 ]]
  [[ $output == "false" ]]
```
The tests are not covering same cases of 'triangle inequality violation'. I think each test should call the script with different combinations of trianagle sides.

```
  run bash triangle.sh isosceles 1 1 3

  run bash triangle.sh isosceles 1 3 1

  run bash triangle.sh isosceles 3 1 1
```

**Comment by guygastineau** [comment]
Thank you for this issue. We need to check the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/triangle/canonical-data.json) for this exercise.

I imagine this was an error in implementing the exercise here, but the canonical-data is probably providing different values for these three cases.

**Comment by guygastineau** [comment]
Great, so looking at the canonical-data it is suggesting exactly what you propose for the values.

Would you like to patch this with a PR?
