### ISSUE TITLE
Resistor Color Trio test case too lenient

### ISSUE THREAD

**Issue by alirezaghey** [exercism/bash#386]
The last three tests in Resistor Color Trio test whether the solution handles invalid input correctly.
The tests only check whether `$output` is empty or not.
https://github.com/exercism/bash/blob/0bad96e891a499c0ba92dd46f93b2de880595fa3/exercises/resistor-color-trio/resistor_color_trio_test.sh#L64

IMHO, it would be better to set an error message to test for. This would also be more in line with the Test Driven Development paradigm, which is somehow what we are doing with the exercises here.

In addition, it may be of value to add tests where some of the arguments are empty or not given at all. This would further narrow down the solutions to be more rigorous (I'm not that savvy to come up with a solution right now that would validate this suggestion, but considering the pitfalls of bash, I imagine that a reasonable possibility).

**Comment by glennj** [comment]
The intent there is that the solution should output *some* error message. It doesn't really matter what the message is.

**Comment by glennj** [comment]
I do notice now we could use a `brown red red == 1200 ohms` test case

**Comment by alirezaghey** [comment]
You mind if I add it?

**Comment by glennj** [comment]
Go for it
