### ISSUE TITLE
Difference of Squares README.md inconsistent with the tests file

### ISSUE THREAD

**Issue by alirezaghey** [exercism/bash#389]
The README.md asks specifically for the **difference between the square of the sum and the sum of the squares**:
https://github.com/exercism/bash/blame/master/exercises/difference-of-squares/README.md#L3

But the tests expect the script to output the **square of the sum**, the **sum of the squares** or the **difference between the two** according to arguments that are passed to the script.

IMHO, the README file is misleading. Either the tests should be changed to only differences or the language in the README should be made broader to encompass all the different types of tests.

**Comment by alirezaghey** [comment]
I'm not sure if I would change the README. Maybe we can change the tests to only check for the correct difference, assuming that one needs to correctly calculate the other parts to come to the correct answer.

The only educational part that is lost in this approach is the conditionals and testing to look what is asked for (sum of, square of, or diff), but I reckon at this stage, conditionals have become secondary, have already been taught, and will be exercised enough throughout the track.

The name of the exercise "Difference of Squares" also adds to the confusion, which we could avoid by only testing for the difference.

**Comment by guygastineau** [comment]
Those tests come from the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/difference-of-squares/canonical-data.json) from the `problem-specifications` repo.

@glennj is right to point out that the tests in question are testing building blocks of the internal implementation.

Any attempt to make such changes to this exercise must happen in `problem-specifications` first.

I thank you for your interest though 😄

**Comment by alirezaghey** [comment]
Then maybe close or change of README? (I'm not sure how I would change the README and keep it concise and clear)

**Comment by NobbZ** [comment]
The [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/difference-of-squares/canonical-data.json) does test for the implementation detail of the helper functions as well.

**Comment by guygastineau** [comment]
If you want there to be a change in the readme that should also happen in the `problem-specificationa` repository.

I take for granted that the readme seems to lack clarity, because I have done the exercise in multiple tracks.  However, I do remember the first time doing this exercise, and the slight confusion I felt.

Ultimately, I think it would be positive for the readme to mention that the tests will test the implementation as well, so please submit a PR to `problem-specifications` 😀

**Comment by alirezaghey** [comment]
Great, thank you for letting me know. I was already doubting myself for the confusion in the first place :sweat_smile:.
I'm closing. Thank you all for the explanation.

**Comment by glennj** [comment]
@alirezaghey I appreciate your continuing interest in making this track better. It's always good to have some fresher eyes looking at things. Keep it up!
