### ISSUE TITLE
INSTALLATION.md

### ISSUE THREAD

**Issue by guygastineau** [exercism/bash#391]
Add suggestion for Mac users to use HomeBrew to get up to date bash installation.

**Comment by guygastineau** [comment]
As discussed in #387

**Comment by guygastineau** [comment]
@glennj do you want to do this or should we put a good first patch and hacktoberfest label on this?

**Comment by glennj** [comment]
PR #393

**Comment by glennj** [comment]
What's the URL for this on the track?

**Comment by guygastineau** [comment]
I don't know exactly. You should be able to find it from the track page.

**Comment by glennj** [comment]
Ah, right. I had to switch to mentored mode to see the docs.

**Comment by guygastineau** [comment]
I will work on information for the most common BSD's before this week is over.

@kotp do you think it is worth providing a link for `AIX` installation?

My initial reaction is: those are normally work servers, so hopefully people aren't actually doing exercism on them.

**Comment by kotp** [comment]
I think it is worth it, but it would be interesting to find out how many people are using it for purposes of learning Bash.

**Comment by guygastineau** [comment]
@kotp do you want me to research and add it with the BSD PR, or do you want to add the `AIX` installation info?

**Comment by kotp** [comment]
Add it in, I think.  We don't do special treatment for HP-UX or other commercial variants, so unsure why AIX is being added in, exactly.  The audience is different, I would think.

**Comment by guygastineau** [comment]
I wasn't aware of any other commercial variants.
