### ISSUE TITLE
We should link to a bash-specific podcast episode

### ISSUE THREAD

**Issue by glennj** [exercism/bash#408]
The podcast [Command Line Heroes](https://www.redhat.com/en/command-line-heroes) did an episode about bash: [https://www.redhat.com/en/command-line-heroes/season-3/heroes-in-a-bash-shell](https://www.redhat.com/en/command-line-heroes/season-3/heroes-in-a-bash-shell). What would be the appropriate place to link to it?

**Comment by kotp** [comment]
I think [RESOURCES.md](https://github.com/exercism/bash/blob/master/docs/RESOURCES.md) is a great place to put notable resources.

**Comment by kotp** [comment]
#422 resolves this issue, I think.
