### ISSUE TITLE
Add .meta/config.json files to exercises

### ISSUE THREAD

**Issue by bkhl** [exercism/bash#412]
To allow automatic test running and to participate in the current Exercism research experiment, each Exercise needs a new `.meta/config.json` file as described in:

https://github.com/exercism/research_experiment_1#config

**Comment by guygastineau** [comment]
Thanks for getting this issue up here @bkhl I will get to this before the end of the week!

**Comment by bkhl** [comment]
The "cmd" parameter was clarified in: https://github.com/exercism/research_experiment_1/issues/32#issuecomment-567836268

**Comment by guygastineau** [comment]
Awesome, that makes sense.

The test runner names are exactly the same as the names for the tests in our BATS files right?

**Comment by bkhl** [comment]
@guygastineau , could you subscribe to the https://github.com/exercism/research_experiment_1/issues/32 issue as well, there's still a bit to be cleared up there.

**Comment by guygastineau** [comment]
Sure thing!
