### ISSUE TITLE
Bowling exercise - 

### ISSUE THREAD

**Issue by braoult** [exercism/bash#426]
tests 15/16/17 will never be done as expected: People simply start script by testing if the number of frames is at least 10 (as in tests 23/24).
Tests 15-17 should have 10 frames, to force solution to handle what is expected (negative roll, and roll > 10).

**Comment by glennj** [comment]
Well, to test if enough rolls to complete 10 frames have been provided, you have to process them, and while you're doing that you can test for invalid rolls and exit early.

If you'd like to make a pull request, have a look at https://github.com/exercism/bash/blob/master/CONTRIBUTING.md

**Comment by braoult** [comment]
Oh, sorry, did not see the output check. Forget about it.
