### ISSUE TITLE
wrong bash beautifier colors

### ISSUE THREAD

**Issue by braoult** [exercism/bash#428]
Not sure if this link is valid, nor if it is on exercism side:
On:
     https://exercism.io/my/solutions/7a25d82ea512403280f7fd168040eefb
... colorization is wrong from line 57, likely from column 21, the quote (') char (which is escaped with "\") looks like a normal quote, which makes all following code wrong.

**Comment by glennj** [comment]
This is not an issue for the bash track. Exercism uses https://github.com/PrismJS/prism for syntax highlighting, so really the bug report should go there.

**Comment by braoult** [comment]
There is a workaround: instead of \'<char> syntax, the "\<char>" seems to be understood by prism. another is to remove the quotes in comments:

Initial faulty lines:
```
printf -v aval "%d" \a                   # 'a' ascii value
printf -v zval "%d" \z                   # 'z' ascii value
```
The following works with prism:
```
printf -v aval "%d" \'a                  # "a" ascii value
printf -v zval "%d" \'z                  # "z" ascii value
```
as well as this :
```
printf -v aval "%d" "'a"                # 'a' ascii value
printf -v zval "%d" "'z"                # 'z' ascii value
```

Looks like prism is "lost" by having the multiple single quotes on same line, for some reason. I will fill a bug report.

**Comment by braoult** [comment]
It has (normally) been fixed in prism:
- bug report : https://github.com/PrismJS/prism/issues/2255
- fix : https://github.com/PrismJS/prism/pull/2256
