### ISSUE TITLE
Consistent quoting of strings in `[[` in `_test.sh`

### ISSUE THREAD

**Issue by IsaacG** [exercism/bash#432]
The test files are somewhat inconsistent in how they treat strings on the right hand side of `[[ foo == bar ]]`.  It's about 50/50 double-quote vs no-quote with a handful of single quotes mixed in.

I was going to make a pull request to make them uniform ... but with the 50/50 split, I'm not sure which way to go. My personal preference would be doube-quote.

Discuss? Or maybe vote with emoji thumbs-up for double-quote, thumbs down for no-quote?

```
$ grep '\[\[ \$[^ ]* == '\" */*test.sh | wc -l
1048
$ grep '\[\[ \$[^ ]* == '\' */*test.sh | wc -l
54
$ grep '\[\[ \$[^ ]* == [[:alnum:]]' */*test.sh | wc -l
1361
```

**Comment by kotp** [comment]
No, the eyes don't mean something else... just that I saw it.  And I don't care, other than it is consistent.  It might be nice to explain what the differences are between single, double and no quotes.

Do we have a style guide that we can refer to for things like this?

**Comment by IsaacG** [comment]
There's the Google Shell Style Guide I help maintain ... but I don't think it talks about it. Ditto on the Wooledge and Bash Hackers wikis. For fixed strings, it really, really, really doesn't matter. For consistent strings, double quotes are going to be the most common.

**Comment by bkhl** [comment]
I'll just state my personal preference:

* quote over no quotes: often gives better syntax highlighting, and it's more obvious it's a string.
* double quotes over single quotes: larger and stand out better when there's no/broken syntax highlighting.
* switch to single quotes it allows fewer escapes.

Unless you want to use a "single format" formatter like Black or Gofmt, I don't think it really matters that much, but I guess it's thumbs up for double quotes for me.

**Comment by glennj** [comment]
Keep in mind that the right hand side of == is a pattern.
```bash
x=foo
[[ $x == f?o ]]
[[ $x == "f?o" ]]
```
Those conditionals clearly have different results.

The unquoted cases will have to be examined on a case by case basis.

I have a very slight preference for double quotes, I think they are more visible.

**Comment by IsaacG** [comment]
I was going to be lazy and grep/sed for patterns that only matched `[[:alnum:]]*` on the RHS for the first pass so that should be fine.
