### ISSUE TITLE
Updates on Bats to Bats Core

### ISSUE THREAD

**Issue by qaws01395** [exercism/bash#438]
I was encountering issues when running bats on my Git bash on Windows. When I read through some conversation online and figured out they have [migrated](https://github.com/sstephenson/bats/pull/234#issuecomment-445023312) to [Bats Core](https://github.com/bats-core/bats-core). 

It works well for me and the testing results looks exactly the same with Bats. Should we update the [Readme](https://github.com/exercism/bash/tree/master/exercises/hello-world#testing) and suggest to use Bats-core instead?

I'm new to open source but I wish to contribute to the community too. Not sure if it's appropriate posting this as a issue.

**Comment by bkhl** [comment]
It seems we started doing that in January but then forgot about it. Started https://github.com/exercism/bash/pull/439 with that branch, with a few additional changes.
