### ISSUE TITLE
Problem with tournament exercise in GHA CI

### ISSUE THREAD

**Issue by glennj** [exercism/bash#460]
I've been working to get github actions CI working. Any commit to master will trigger the full test suite for all exercises. The Tournament exercise is currently failing.

At an interactive bash prompt, there's nothing wrong with the tournament exercise:
```bash
$ bin/validate_one_exercise exercises/tournament
Processing tournament
 ✓ just the header if no input
 ✓ a win is three points, a loss is zero points
 ✓ a win can also be expressed as a loss
 ✓ a different team can win
 ✓ a draw is one point each
 ✓ There can be more than one match
 ✓ There can be more than one winner
 ✓ There can be more than two teams
 ✓ typical input
 ✓ incomplete competition (not all pairs have played)
 ✓ ties broken alphabetically

11 tests, 0 failures

Updated 1 path from the index
```

But upon commit to master, CI fails (https://github.com/exercism/bash/runs/1376729353):
```bash
Processing tournament
1..11
ok 1 just the header if no input
not ok 2 a win is three points, a loss is zero points
# (in test file tournament_test.sh, line 47)
#   `[[ $output == "$expected" ]]' failed
ok 3 a win can also be expressed as a loss
ok 4 a different team can win
ok 5 a draw is one point each
ok 6 There can be more than one match
ok 7 There can be more than one winner
ok 8 There can be more than two teams
ok 9 typical input
not ok 10 incomplete competition (not all pairs have played)
# (in test file tournament_test.sh, line 223)
#   `[[ $output == "$expected" ]]' failed
ok 11 ties broken alphabetically
Updated 1 path from the index
Error: Process completed with exit code 1.
```
This behaviour can be reproduced, with
```bash
$ echo "" | bin/validate_one_exercise exercises/tournament
```

The 2 tests that are failing are where input is redirected into the script's stdin. The [`[[ -t 0 ]]` check in the example.sh](https://github.com/exercism/bash/blob/master/exercises/tournament/example.sh#L3) is not returning the expected value, and the tests fail because the shell does not see the input data.

It appears that CI in GHA is not providing a tty to the validation scripts.

More evidence:

* a [commit to master on my fork](https://github.com/glennj/exercism-bash/commit/c84d4231b1fc38b7283ffbc764f395c5e90958d5)
* that has [this CI output](https://github.com/glennj/exercism-bash/runs/1376980621)

These are pretty important tests, educationally speaking, IMO.

So, what to do?

**Comment by glennj** [comment]
@exercism/maintainers-admin can I get your thoughts on this? In a nutshell, we have an exercise where some tests do:
```bash
run bash tournament.sh fileContainingData
```
and some tests do
```bash
run bash tournament.sh <<<END
the data
is provided
on stdin
END
```
These latter tests are failing in GHA CI.

**Comment by iHiD** [comment]
(cc @exercism/github-actions)

**Comment by SaschaMann** [comment]
> It appears that CI in GHA is not providing a tty to the validation scripts.

Maybe related to this https://github.com/actions/runner/issues/241?

I don't know bash well enough to know how to work around this issue.

**Comment by cmccandless** [comment]
As a workaround, running the tests inside in separate docker container with `docker run -t`might work. I can put together a test PR tomorrow.

**Comment by glennj** [comment]
Has been worked-around.
