### ISSUE TITLE
Error Handling exercise planning

### ISSUE THREAD

**Issue by jaggededgedjustice** [exercism/bash#47]
What should the error handling exercise cover for bash? The current list I can think of would be:
* Argument validation
* set -e
* set -u

Are there others?

Though I’m not sure how to test usage of the set flags . Perhaps the argument validation would be enough, that could resolve the remaining concerns from #29.

**Comment by kotp** [comment]
Specifically for the Hello World exercise or a new exercise?

**Comment by jaggededgedjustice** [comment]
New exercise, https://github.com/exercism/x-common/blob/master/exercises/error-handling/description.md

**Comment by kotp** [comment]
In that case, definitely pile them up.

Does `getopts` give you the information for the set flags?

**Comment by vlisivka** [comment]
Typical "safe" bash script uses `set -ue`, sometimes `set -ue -o pipefail`. I wrote whole library for bash which works with `set -ue` options.

**Comment by jaggededgedjustice** [comment]
It turns out the $SHELLOPTS variable will contain values for the things controlled via set. So `echo $SHELLOPTS | grep ...` can tell you if a specific flag was used.

**Comment by jaggededgedjustice** [comment]
I added #49. It doesn't do anything with 'set', the script being tested is run in a sub shell and the 'set -eu' options aren't inherited and don't escape a subshell. So I can't see a way to write a test and verify that a given option was used by the script. Also, bats is doing a 'set -e' which will be visible if you're trying to check SHELLOPTS after running your script.

**Comment by vlisivka** [comment]
+jaggededgedjustice Why not to use `source` instead of `run` in this particular case?

**Comment by jaggededgedjustice** [comment]
I had been thinking of having separate steps for each thing, so 1 function for arg checking, a different function to demonstrate use of 'set -e' and so on. But I can't see how to make that work, so maybe it's just 1 script and then it can be sourced to check the use of set flags. Depends if there are other situations to address besides arg checking.

**Comment by kytrinyx** [comment]
Closed by #49
