### ISSUE TITLE
Add diffing support to bash tests

### ISSUE THREAD

**Issue by MichaelDimmitt** [exercism/bash#531]
Diffing is easy to attain in bats
If you add printDiff to every function. 
It will only show the output if the test fails.

curious if @IsaacG has thoughts.

by changing
```bash
@test "a name given" {
  [[ $BATS_RUN_SKIPPED == true  ]] || skip
  run two_fer Alice
  [[ $status -eq 0 ]]
  [[ $output == "One for Alice, one for me." ]]
}
```
```bash
printDiff(){
  echo output;
  echo "$output";
  echo ;
  echo expected;
  echo "$expected;
}

@test "a name given" {
  [[ $BATS_RUN_SKIPPED == true  ]] || skip
  run two_fer Alice

  expected=$(cat <<-END
One for Alice, one for me.
END
  )

  printDiff
  [[ $status -eq 0 ]]
  [[ "$output" ==  "$expected" ]]
}
```

This actually just saved me on a project.
And I am sourcing the scripts like libs as is proposed in the pending pr
https://github.com/exercism/bash/pull/373

**Comment by IsaacG** [comment]
My name was mentioned?

Drop the trailing semicolons. Use snake case naming consistently, including function names. Prefer printf over echo. Replace your `$(cat <<<END ... foo)` with `"foo"`. Prefer `((` over `[[` for numeric tests (`-eq 0`). Only print diff when there is a diff.

**Comment by IsaacG** [comment]
If you're going to show diffs, you may want to actually show the diff, not just the want/expect. `diff` is usually installed on most boxes that support bash. Maybe `diff -u0 <("$want") <("$got")`

**Comment by MichaelDimmitt** [comment]
Sorry about the mention, you always give great feedback
thanks for the insight I will try it out `diff -u0 <("$want") <("$got")`

**Comment by IsaacG** [comment]
@MichaelDimmitt Feel free to mention me any time you want someone pedantic to nitpick your shell code :)

**Comment by MichaelDimmitt** [comment]
## Went with cmp for readibility purposes
also started a discussion on bats-core 🎉 https://github.com/bats-core/bats-core/issues/490
```bash
printDiff(){
  echo ;
  echo output;
  echo "$output";
  echo ;
  echo expected;
  echo "$expected";
  echo ;
  cmp <(echo "$output") <(echo "$expected") | cut -c 23-;
  echo ;
}

@test "a failure on line 1" {
  run bash two_fer.sh Alice
  expected=$(cat <<-END
test should fail
this is some text
END
  )
  output=$(cat <<-END
test should pass
this is some text
END
  )
  printDiff
  [[ "$output" == "$expected" ]]
}
@test "a failure on line 2" {
  run bash two_fer.sh Alice
  expected=$(cat <<-END
this is some text
test should fail
END
  )
  output=$(cat <<-END
this is some text
test should pass
END
  )
  printDiff
  [[ "$output" == "$expected" ]]
}
@test "a bad diff occurs if expected is 2 lines but output is 1 line" {
  run bash two_fer.sh Alice
  expected=$(cat <<-END
this is some text
test should fail
END
  )
  output=$(cat <<-END
this is some text
END
  )
  printDiff
  [[ "$output" == "$expected" ]]
}
```
<img width="700" alt="Screen Shot 2021-08-22 at 11 11 45 AM" src="https://user-images.githubusercontent.com/11463275/130360371-db3e0e20-1afc-4225-9b89-685eea6d0e85.png">

**Comment by IsaacG** [comment]
On a successful test, will this echo the output two times?

**Comment by MichaelDimmitt** [comment]
on a successful test bats does not provide any output other than that the test passed.

**Comment by glennj** [comment]
I'm  coming around to this. With the v3 release of exercism, showing students that `[[ $output == $expected ]] fails` is just insufficient information.
