### ISSUE TITLE
Pangram test fails with "bad substitution"

### ISSUE THREAD

**Issue by austinmlv** [exercism/bash#557]
The tests for 'pangram' pass locally but fail on the exercism website. I think this is possibly due to different versions of bash and/or bats between my machine and the exercism website. Can anyone direct me to where I might find with version of bash and bats the website is using?

On my machine `bash --version` reports the following: `GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)`
and `bats --version` reports: `Bats 1.5.0`

Here's the error on the exercism website:
```
(from function 'assert_success' in file bats-extra.bash, line 409,
 in test file pangram.bats, line 11)
  'assert_success' failed

-- command failed --
status : 1
output : pangram.sh: line 34: input=${1@L}: bad substitution
--
```
I get the same error for each of the 10 tests. The line that fails is `local input=${1@L}` in the function `main`.
Here is my code that works on my machine (shellcheck reports nothing):
```bash
#!/usr/bin/env bash

char() {
    printf "%b" "\\$(printf %o "$1")"
}

initialize_alphabet() {
    for((i=97; i < 123; i++)); do
        alphabet["$(char "$i")"]=0
    done
}

record_letters_used() {
    local input=$1
    for((i=0; i < ${#input}; i++)); do
        character="${input:i:1}"
        if [[ "$character" =~ [[:alpha:]] ]]; then
            alphabet["$character"]=1
        fi
    done
}

count_letters_used() {
    declare -i letters=0
    for letter in "${alphabet[@]}"; do
        if ((letter == 1)); then
            ((letters += 1))
        fi
    done
    echo "$letters"
}

main() {
    local input=${1@L}
    local -A alphabet
    initialize_alphabet
    record_letters_used "$input"
    if (("$(count_letters_used)" == 26)); then
        echo "true"
    else
        echo "false"
    fi
}

main "$@"
```

**Comment by IsaacG** [comment]
Note `${var@L}` was only introduced fairly recently in v5.1. `bash 4.0` introduced a similar feature, `${var,,}`, which would be compatible with older shells.

The more general "issue" here is that Exercism's exercise runner VM is not running the latest version of bash. Infrastructure needs continuous upkeep and moving things to newer versions. Apparently the bash upgrade to 5.1 has not yet happened.

**Comment by austinmlv** [comment]
Thank you @IsaacG! I used the `${var,,}` expansion and it's working as expected. Do you know in which repository I can find the infrastructure information? Is it specific to each track or specific to the exercism/website repo? I have similar issues with the scheme track and don't know where to find the versions of software being run under that track's infrastructure too. Thanks again.

**Comment by austinmlv** [comment]
I think I found the information I was looking for in the exercism/bash-test-runner/Dockerfile.

**Comment by glennj** [comment]
@austinmlv do you think it would make sense to tell you (somewhere) that the test runner uses bash 5.0? Where would that information be placed?

**Comment by austinmlv** [comment]
@glennj Maybe on the 'about' page for the bash track? Something like "Exercism uses Bash version 5.0 so make sure your solutions conform to that version"? Unless it's mentioned on the Exercism website and I overlooked it...

**Comment by kotp** [comment]
If we can show it in the test runner, pass or fail, that might be a good place for it.  If it is in the README, it may end up being wrong part of the time (if that is forgotten to be updated.)  But the test is the actual environment.
