### ISSUE TITLE
Not running tests with `bash` specifically

### ISSUE THREAD

**Issue by glennj** [exercism/bash#558]
I had a mentoring session where the student wanted to write portable code.

To facilitate this, we could do, for each exercise:
* at the top of the bats file, add `chmod u+x ./exercise.sh`
* each test can then `run ./exercise.sh ...`

I think we need to explicitly call chmod because I don't think we can rely on git/exercism to maintain executable bits.

This would allow the students to use whatever shebang they want, but it would cease to be the **bash** track.

We could take the opportunity to remove the ".sh" extension from the skeleton files.

Any thoughts?

**Comment by glennj** [comment]
I didn't mean to assign, I meant to tag: @IsaacG @kotp @guygastineau

**Comment by kotp** [comment]
How would we ensure that the tests are passable given the different potential different sh'bang?  Would there be a list of "target" shells?

**Comment by glennj** [comment]
good point.

**Comment by IsaacG** [comment]
I'm in favor of keeping this a `bash` track. 

* Some of these exercises are painful using POSIX `sh`. 
* If this is generic "shell of your choice", it'd be weird to have some students trying to use `zsh` when mentors might not be familiar. Or `ksh` and `csh`. Those are all different languages and not `bash`.

If a student wants to write POSIX `sh` and the mentor is comfortable with `sh`, then that's cool. But I don't think we should be going out of our way to make that the easy route.

**Comment by kotp** [comment]
And the difference between invoking via `bash` or `sh`, using `source` and making executables is very much something that can be taught about bash shells.

**Comment by glennj** [comment]
I appreciate the feedback. Closing this issue.

**Comment by kotp** [comment]
There could be an exercise specifically about "portable code" and with only one or two exercises, the idea of making it executable, and writing it so that it can be loaded / sourced as a non-clobbering function.  Or notes added about portability, and what approaches are POSIX and what may cause problems with different platforms and tooling.

**Comment by glennj** [comment]
Hmm, maybe a refactoring-type exercise, where they're given a script loaded with bashisms and they need to make it POSIXy

**Comment by IsaacG** [comment]
I feel like that's out of place on a bash track. This track is about the bash shell. We should be helping students learn bash, including all it's features. Having an exercise where students are then supposed to not use all the features and make their script work for a very different environment feels ... jarring?

If a student wants to write POSIX sh, they can simply set `POSIXLY_CORRECT` and do so. I don't think other students should be asked to do so as part of solving exercises on the bash track.

**Comment by kotp** [comment]
I am definitely one for "go where the student wants to go" as it is their learning journey.  And this is one way to do that.  If the student asks "But what about portability?" then they can go down that path.
