### ISSUE TITLE
command rev is not always working in exercism tests

### ISSUE THREAD

**Issue by Kidlike** [exercism/bash#561]
Hi,

I was implementing https://exercism.org/tracks/bash/exercises/luhn, and I tried to use `rev` to reverse the input string, so I can iterate in a positive loop (starting from 0 index).

While locally this worked fine, when I submitted it, one of the tests executed by exercism.io failed:
```
run bash luhn.sh "055£ 444$ 285"
assert_success
assert_output "false"
```

```
(from function `assert_output' in file bats-extra.bash, line 394,
 in test file luhn.bats, line 94)
  `assert_output "false"' failed

-- output differs --
expected (1 lines):
  false
actual (2 lines):
  rev: stdin: Invalid or incomplete multibyte or wide character
  false
--
```

---

I don't know if it's in the spirit of this track to use such commands, but I thought I should report this regardless :)

**Comment by glennj** [comment]
I'd have to see your code, and what you're feeding into rev. Can you paste a link to it, or a mentoring invitation?

As a guess, try moving the error checking earlier in your code, so that non-digits are detected before piping them into rev.

**Comment by Kidlike** [comment]
You're right, that I could use `rev` after validating the input; but I solved it without using rev at all, which I guess is even better in the spirit of the bash track.

Regardless, this error comes from running `input=$(echo -n "${*//\ /}" | rev)` as the first command in the script.

The question is more like, should this _generally_ work or not? From some googling it looks like this problem is system-related (OS? packages? locale config? not sure...)

**Comment by IsaacG** [comment]
The exercise can (and should) be solved via `bash` and not other utilities. `rev` is part of `util-linux` and may or may not exist on BSD or MacOS. It may differ from distro to distro. The behavior of other utilities that may or may not exist in the test environment should, as much as possible, be out of scope of these exercises.

I could create a similar bug about how executing `python <<< 'print("foo".removeprefix("f"))' might not work because the image doesn't contain Python 3.9. It's not `bash` related though.

**Comment by matt-kita** [comment]
> The exercise can (and should) be solved via `bash` and not other utilities. `rev` is part of `util-linux` and may or may not exist on BSD or MacOS. It may differ from distro to distro. The behavior of other utilities that may or may not exist in the test environment should, as much as possible, be out of scope of these exercises.

Right. Additionally - `rev` works on a line-by-line basis, not on a character-by-character basis, so the newline characters ordering a.k.a. line ordering (if any newlines are present in the input) is also not reverted. The questions remain: should it be reverted as well? should it be tested somehow?

Example:
`$ rev <<<'helo *  world
newline?'
dlrow  * oleh
?enilwen
$ main 'helo *  world
newline?'
?enilwen
dlrow  * oleh
$`

**Comment by IsaacG** [comment]
I think a test which includes newlines would be a valuable addition here.

**Comment by glennj** [comment]
Raised in exercism/problem-specifications#2073

**Comment by glennj** [comment]
Community consensus is to put "more advanced" reverse cases into a new exercise.

Closing this issue.
