### ISSUE TITLE
Tests for armstrong-numbers exercise do not cover numbers with leading zeros

### ISSUE THREAD

**Issue by sponomarev72** [exercism/bash#563]
The armstrong exercise https://exercism.org/tracks/bash/exercises/armstrong-numbers does not test numbers that have leading zeros. E.g. there is a test for `153` but no test for `00153`.

**Comment by glennj** [comment]
What is the purpose of that test?

**Comment by sponomarev72** [comment]
When a number with leading zeros is passed to the solutions currently published they all fail because they calculate actual length of the number wrong and use this incorrect number as exponent to compute power.
From solution perspective, it will require students to trim leading zeros before calculating the exponent.

**Comment by IsaacG** [comment]
There's nothing in the spec which indicates leading zeros need to be trimmed.

Additionally, usually ints don't have leading zeros.

This sounds sorta contrived simply for the purpose of adding additional requirements to the solution. I don't think this is "needed" for a solid, working solution.

**Comment by kotp** [comment]
In many languages integers with leading 0's are not integer but instead would be considered octal.  The point might be an exercise in itself for someone coming from another language.

**Comment by IsaacG** [comment]
@sponomarev72 Any further thoughts or should I close out this issue?

**Comment by sponomarev72** [comment]
@IsaacG I think it can be closed. I probably don't exactly understand reasoning behind what should be part of a problem and what should not. Maybe there is a document clarifying this question but I have not seen it. I believe such document could be useful. Since there are concerns about my suggestion I'm fine with closing it.
