### ISSUE TITLE
Topics: what is hamming about?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/bash#66]
In preparation for the launch of the Exercism redesign, we need to decide what topics to list for hamming.
See https://github.com/exercism/bash/issues/61 for context.

@ConstantlyLost, @canel-rom1, @dantiel, @deepbsd, @fwten, @mattj-io, @mkrehbs, @patbl, @rpalo, @timmyjose - Having solved this, what would you say that hamming is about? Did you struggle with anything in particular? What did you learn?

**Comment by sjwarner-bp** [comment]
Closed via #128
