### ISSUE TITLE
Foregone exercises

### ISSUE THREAD

**Issue by glennj** [exercism/bash#665]
The foregone list in the track config.json is current unset.

Suggested list of bash exercises to forego

1. alphabetics
1. bank-account
1. binary-search-tree
1. book-store
1. circular-buffer
1. complex-numbers
1. connect
1. custom-set
1. diffie-hellman
1. dominoes
1. dot-dsl
1. etl
1. flatten-array
1. go-counting
1. grade-school
1. hangman
1. high-scores
1. killer-sudoku-helper
1. ledger
1. lens-person
1. linked-list
1. matrix
1. micro-blog
1. paasio
1. parallel-letter-frequency
1. pov
1. react
1. rest-api
1. robot-name
1. saddle-points
1. sgf-parsing
1. simple-linked-list
1. state-of-tic-tac-toe
1. strain
1. tree-building
1. word-search
1. zebra-puzzle
1. zipper

**Comment by glennj** [comment]
Currently implemented but deprecated
- beer-song
- diffie-hellman

Do we want to remove and forego these?

**Comment by glennj** [comment]
That would leave as merely unimplemented:

1. bottle-song
1. minesweeper

**Comment by IsaacG** [comment]
> Currently implemented but deprecated
> 
> 1. beer-song
> 2. diffie-hellman
> 
> Do we want to remove and forego these?

Happy to remove them if they are deprecated. I don't think they need to be marked as foregone if they are deprecated, though.

**Comment by IsaacG** [comment]
I didn't think about them too hard but these may be viable:
* hangman
* robot-name
* state-of-tic-tac-toe

**Comment by glennj** [comment]
You'll have to convince me about hangman. Its description talks about "functional reactive programming". I ignored that in Tcl and went with creating a TCP server to receive guesses. But I don't see ATM what approach to take to test a bash implementation.

**Comment by glennj** [comment]
> I don't think they need to be marked as foregone if they are deprecated, though.

Otherwise they'll just show up as "not yet implemented". IMO foregoing is the maintainer's way of saying "we thought about it and decided not to".

**Comment by IsaacG** [comment]
> You'll have to convince me about hangman. Its description talks about "functional reactive programming". I ignored that in Tcl and went with creating a TCP server to receive guesses. But I don't see ATM what approach to take to test a bash implementation.

I could be mistaken but I think most tracks ignore that bit and treat it as a regular functional assignment that stores state via a class or something.

**Comment by glennj** [comment]
From what I can tell with my GitHub search-fu: java, C#, F#, OCaml are FRP exercises; python and Powershell are simpler OO exercises; Tcl is an event-based exercise; no other tracks.

But I can now picture what we might want to do: launch the program with the word, and send guesses on stdin
```sh
bash hangman.sh puppy << GUESSES
p
a
r
t
y
o
n
w
a
y
n
e
GUESSES
```
would output something like
```
9 p P_PP_
8 a P_PP_
7 r P_PP_
6 t P_PP_
6 y P_PPY
5 o P_PPY
4 n P_PPY
3 w P_PPY
2 a P_PPY
1 n P_PPY
0 e P_PPY lose
```

**Comment by IsaacG** [comment]
We could also pass in info using $1 vs other args and/or exported env vars.

**Comment by glennj** [comment]
> That would leave as merely unimplemented:
> 
> 1. bottle-song
> 2. minesweeper

I forgot to mention 

3. resistor-color

Not sure why we have -duo and -trio but not the original.

**Comment by kotp** [comment]
> * hangman

I was about to respond the same about hangman.  Seems like a fairly good fit, reminds me of early days learning to write programs late at night when I was supposed to be sleeping, for my younger sister learning to spell and read.
