### ISSUE TITLE
Topics: what is raindrops about?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/bash#68]
In preparation for the launch of the Exercism redesign, we need to decide what topics to list for raindrops.
See https://github.com/exercism/bash/issues/61 for context.

@canel-rom1, @dantiel, @fwten, @mattj-io, @mkrehbs, @patbl, @timmyjose - Having solved this, what would you say that raindrops is about? Did you struggle with anything in particular? What did you learn?

**Comment by sjwarner-bp** [comment]
Closed via #128
