### ISSUE TITLE
Topics: what is word-count about?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/bash#69]
In preparation for the launch of the Exercism redesign, we need to decide what topics to list for word-count.
See https://github.com/exercism/bash/issues/61 for context.

What topics would you say that word-count touches upon?

**Comment by kotp** [comment]
#48 is missing the test for this exercise, but needs a test suite.  See that issue for branch information.

Text analysis
Strings

**Comment by sjwarner-bp** [comment]
Closed via #128
