### ISSUE TITLE
Two-fer readme talks about tdd like it's the second exercise

### ISSUE THREAD

**Issue by Smarticles101** [exercism/bash#86]
So two-fer is meant to be the second exercise, but it's a little too difficult to be the second one on bash ([986b124](https://github.com/exercism/bash/commit/986b12455ed4c1e0190507161999d0a2d49f2780)), so gigasecond is. However, because the readme's are generated, the two-fer readme explains test driven development like it is the second exercise. Is there a fix for this as far as generation goes @kytrinyx? @exercism/configlet?

**Comment by NobbZ** [comment]
Just delete that section from the README should work…

**Comment by robphoenix** [comment]
@Smarticles101 The Go README is in the process of being updated by @tleen to document this, the PR may help with this: https://github.com/exercism/go/pull/846

**Comment by kytrinyx** [comment]
You could add the section to a file named `.meta/hints.md` in the `gigasecond` exercise, which would add the TDD part to the gigasecond exercise.

We probably shouldn't assume that two-fer is the second exercise in problem-specifications.
