### ISSUE TITLE
Create skeleton files for exercises

### ISSUE THREAD

**Issue by budmc29** [exercism/bash#87]
Do we need to create the code files for Bash? I see some languages have that implemented, and some don't.

Reference https://github.com/exercism/python/commit/de66a31bb7100ebcb2b19c0bec54184ce61ffdd8#diff-3ac5069a6087f5b553775a0720254dc1

**Comment by Smarticles101** [comment]
I know on the java track we have a policy to only include skeleton files for the first like 20 exercises or so. We could potentially do something like this on the bash track, but the tests are just using testing against output of the script. I'm not sure that there's really much we could put in skeletons like method headers and such that would usually be in them on other tracks

**Comment by budmc29** [comment]
I was thinking about something along these lines:
```
#!/usr/env/bin bash

function main() {
  # Add your code here
}

main
```

**Comment by Smarticles101** [comment]
That seems like a good idea. We could also include variables simply getting the input passed in. Thoughts @exercism/bash?

**Comment by kenden** [comment]
@Smarticles101 variables getting the input passed in, could you detail more what you're thinking about?

Also, I'd like some nice default included. [This page](http://kvz.io/blog/2013/11/21/bash-best-practices/) has a few nice ones. At least the the `set` commands?

**Comment by Smarticles101** [comment]
@kenden Like `input="$1";`

**Comment by budmc29** [comment]
@sjwarner-bp what is your opinion on this?

**Comment by sjwarner-bp** [comment]
I think that this could be a good idea - but maybe only for the first few exercises?

On the Java track, they have chosen to put skeleton files in for all exercises under a '4' difficulty. I don't think this would work for us, because most of our exercises are below 4 (revamp and re-estimation of difficulty to come now the pending exercise PRs have been merged)!

I'd suggest maybe adding them just to core exercises. While it is useful for first-time users, part of learning to write in Bash is learning to do it from scratch :sli

**Comment by budmc29** [comment]
Looks like we have reached an agreement and we are all in favor of adding a skeleton for the exercises.

> I think that this could be a good idea - but maybe only for the first few exercises?
@sjwarner-bp 

That's a very good idea, combining the both worlds. Getting the users familiar with a good script structure and they can decide to keep it and use it for the next exercises or just delete it and use whatever they like.

**Comment by sjwarner-bp** [comment]
@budmc29 which approach do you think we should go with then?

I think either of 'core' exercises or 'exercises under a 4 difficulty' could work. What do you prefer?

**Comment by budmc29** [comment]
All the core exercises would be too much, from what I see most users finish the first few exercises, so maybe the first 4-5.

I have a bunch of similar PR to do tonight, so I'll include this as well.

**Comment by sjwarner-bp** [comment]
Which exercises should we put these on?

I've just thought of another thing related to this.

On the Java track, we had a few confused users ask where the skeleton files 'disappear to' on later exercises (i.e. they get confused when they are no longer supplied these files).

Might it be worth adding a `hints.md` to explain to a user how to make their own files in the exercises immediately after the skeleton file exercises?

**Comment by budmc29** [comment]
In that case we could either create a template for all the exercises, and the users that do not want to use it will delete the content and keep the file, or just create the hello_world.sh template and add a notice in there that it will not be supplied for the other exercises but they can copy it over.

**Comment by sjwarner-bp** [comment]
> or just create the `hello_world.sh` template and add a notice in there that it will not be supplied for the other exercises but they can copy it over.

I prefer this approach - it makes more sense in my opinion. We can add the notice in a `.meta/hints.md` which will automatically get pulled in when the README is regenerated using `configlet`.
