### ISSUE TITLE
Decision: Plain Bash or POSIX compliance?

### ISSUE THREAD

**Issue by budmc29** [exercism/bash#88]
It might be a good idea to have the discussion about this in this separate issue.

As @kenden stated here: https://github.com/exercism/bash/issues/4#issuecomment-326548299, we need to decide what are the requirements for this track.
> Kenden: I vote for: only bash, no extra utilities needed, no posix/sh/zsh compatibility required.

I agree to that, we should just teach plain Bash with no extra requirements or POSIX compliance in the code or in the tests.  

Learning bash is difficult and for most of the users (especially the targeted users for exercism v2), and the majority of the use cases for bash is to create scripts to aid in development, which means the environment is similar or at least known.

What do you think?

**Comment by Smarticles101** [comment]
I agree for all the same reasons

**Comment by kenden** [comment]
Same decision to make for bats: https://github.com/bats-core/bats-core/issues/28

**Comment by Smarticles101** [comment]
When creating example exercises, should we allow use of extra commands that are not necessarily a part of bash? Of course, the student should ultimately be able to solve an exercise however they want, but some exercises become a lot more difficult without extra commands. i.e. `gigasecond`s usage of the `date` command

**Comment by sjwarner-bp** [comment]
I think we don't necessarily need to enforce POSIX compliance, as exercism is a learning tool and this might seem to be too complex (or just a bit excessive) for new users.

Please correct me if I am mistaken, but just because we don't enforce POSIX compliance doesn't mean that users cannot submit this kind of solution? In this case, we could add a small blurb about POSIX at the end of READMEs as a stretch goal or reminder?

**Comment by kotp** [comment]
I like the POSIX stretch goal idea.

**Comment by budmc29** [comment]
Looks like we have a decision and we can act on it :D.

- Don't enforce POSIX compliance for our internal code, or code submitted as the solution and we allow users to use any utilities as long as the test passes on their system.
- Have POSIX compliance as a stretch goal

For the stretch goal that could be a good start for a discussion when users submit their solutions.
